'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Maximized")>  _
        Public Property TamanoVentana() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("TamanoVentana"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("TamanoVentana") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30, 30, 30")>  _
        Public Property ColorFondo() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorFondo"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorFondo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50, 50, 50")>  _
        Public Property ColorContornos() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorContornos"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorContornos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FloralWhite")>  _
        Public Property ColorFuentes() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorFuentes"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorFuentes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Crimson")>  _
        Public Property ColorLineas() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorLineas"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorLineas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lua")>  _
        Public Property LenguajeSeleccionado() As Global.FastColoredTextBoxNS.Language
            Get
                Return CType(Me("LenguajeSeleccionado"),Global.FastColoredTextBoxNS.Language)
            End Get
            Set
                Me("LenguajeSeleccionado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50, 50, 50")>  _
        Public Property ColorIndentacion() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorIndentacion"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorIndentacion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30, 30, 30")>  _
        Public Property ColorHerramientas() As Global.System.Drawing.Color
            Get
                Return CType(Me("ColorHerramientas"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ColorHerramientas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Courier New, 10pt")>  _
        Public Property TipoDeFuente() As Global.System.Drawing.Font
            Get
                Return CType(Me("TipoDeFuente"),Global.System.Drawing.Font)
            End Get
            Set
                Me("TipoDeFuente") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Idioma() As Boolean
            Get
                Return CType(Me("Idioma"),Boolean)
            End Get
            Set
                Me("Idioma") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PrimerInicio() As Boolean
            Get
                Return CType(Me("PrimerInicio"),Boolean)
            End Get
            Set
                Me("PrimerInicio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property rutaProyecto() As String
            Get
                Return CType(Me("rutaProyecto"),String)
            End Get
            Set
                Me("rutaProyecto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Nuevo() As Boolean
            Get
                Return CType(Me("Nuevo"),Boolean)
            End Get
            Set
                Me("Nuevo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ClicInicio() As Boolean
            Get
                Return CType(Me("ClicInicio"),Boolean)
            End Get
            Set
                Me("ClicInicio") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.RedSky_Ruby_IDE.My.MySettings
            Get
                Return Global.RedSky_Ruby_IDE.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
